version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:8099:80"               # фронтенд (Nginx) слушает порт 80 на хосте
    depends_on:
      - backend
      - server
    restart: always

  backend:
    build: ./backend
    # Внешний порт для backend не публикуем (доступен через фронтенд)
    restart: always

  server:
    build: ./server
    # Внешний порт для server не публикуем (доступен через фронтенд)
    restart: always
