version: '3.8'

services:
  server:
    build:
      context: ./server
      target: production
    environment:
      - NODE_ENV=production
      - PORT=3001
    # Внешний порт для server не публикуем (доступен через фронтенд)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - "127.0.0.1:8099:80"               # фронтенд (Nginx) слушает порт 80 на хосте
    depends_on:
      - server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

# Добавляем общую сеть для сервисов
networks:
  default:
    driver: bridge
