version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: encounter-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env         # <- если нужен .env с переменными (PORT, DB_URL, JWT_SECRET и пр.)
    ports:
      - "5000:5000"            # API будет слушать 5000
    networks:
      - encounter-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: encounter-frontend
    restart: unless-stopped
    # Frontend сам по себе отдаёт статику на 80-й (nginx внутри контейнера),
    # но мы НЕ выставляем наружу порт 80 — выход из браузера пойдёт через контейнер server.
    networks:
      - encounter-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: encounter-server
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"                # Единая точка входа — всё пойдёт на этот порт
    networks:
      - encounter-network

networks:
  encounter-network:
    driver: bridge
